server:
  port: 8061
spring:
  application:
    name: spring-boot-mybatis-plus-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.29.130:5455/rag_flow?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: infini_rag_flow
mybatis-plus:
  mapper-locations: classpath*:/mapper/**.xml
  type-aliases-package: com.demo.entity
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: ASSIGN_UUID
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false